package com.cqrs.query.entities;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.UUID;

@Document(collection = "products")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class Products {

    @Id
    private String pId; // MongoDB ID

    private String id; // ID from Kafka message
    private String name; // Corresponds to "name" in JSON
    private Double price;
    private String description; // Corresponds to "description" in JSON
    private String uuid;

    // Getters and Setters are generated by Lombok
}
